id: I68AC6856
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T12:36:05+00:00'
last_modified: '2022-06-08T13:05:49.230330+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD408
  title: གསང་ཐུས་ཐིག་ལེའི་བཀོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B484:
      image_group_id: I2PD18037
      title: ''
      total_pages: 332
      order: 1
      base_file: B484.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
