id: P010370
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3PD408
  title: གསང་ཐུས་ཐིག་ལེའི་བཀོད་པ།
  author: ''
  volumes:
    a599ae49fb3d459aa5734b6813864b57:
      image_group_id: I2PD18037
      title: ''
      volume_number: 1
      total_pages: 332
      base_file: v001.txt
